Feat: Ethereum account details page
superhero-com/superhero-wallet pull request #2501
Opened 2023-11-08 12:54 UTC by peronczyk

2023-11-14 11:00 UTC, martinkaintas requested changes
lgtm but I think the 2 identical commits should be dropped
Probably appeared during a rebase

2023-11-15 08:39 UTC, peronczyk commented
> lgtm but I think the 2 identical commits should be dropped Probably appeared during a rebase

True. I squashed the commits.

2023-11-15 08:57 UTC, CedrikNikita approved these changes

2023-11-15 09:13 UTC, martinkaintas approved these changes

2023-11-15 12:56 UTC, dvdbak commented
LGTM

2023-11-16 07:52 UTC, merged