fix: dex missing compiler issue through in-app browser
superhero-com/superhero-wallet pull request #2580
Opened 2023-12-14 12:34 UTC by martinkaintas

2023-12-15 10:57 UTC, CedrikNikita requested changes
Previously our goal was to completely remove our dependency on http compiler, resolving this issue (I'm not sure what exactly is the problem) like that is a step back in my opinion.

2023-12-15 11:35 UTC, martinkaintas commented
> Previously our goal was to completely remove our dependency on http compiler, resolving this issue (I'm not sure what exactly is the problem) like that is a step back in my opinion.

I completely agree with you, the issue is that I suppose the DEX is relying on the compiler for some actions.
If you try to reproduce the [linked issue](https://github.com/superhero-com/superhero-wallet/issues/2571) you'll see that we get an error that the compiler is not ready.

2023-12-18 07:47 UTC, peronczyk approved these changes

2023-12-18 09:15 UTC, martinkaintas commented
CompilerHttp has been deprecated. Same functionalities available using the JS lib https://github.com/aeternity/aepp-calldata-js
This issue should probably be fixed in the DEX

2023-12-18 09:15 UTC, closed without merging