Fix deeplinks on mobile
superhero-com/superhero-wallet pull request #2694
Opened 2024-02-06 13:29 UTC by CedrikNikita

fixes #2554,
fixes #2687

2024-02-06 13:39 UTC, martinkaintas approved these changes

2024-02-06 14:35 UTC, peronczyk commented
Why those components has the `Loader` component imported now? Maybe the global `loading` state can be used?

2024-02-06 14:36 UTC, Liubov-crypto commented
Fixed, LGTM

2024-02-06 15:39 UTC, peronczyk requested changes

2024-02-06 15:39 UTC, peronczyk commented on src/popup/router/index.ts
> +          const query = event.url.slice(prefix?.length).split('?')[1].split('&').reduce((acc, param) => {
This is the 2nd time where similar logic is used. I suggest to use: 

```
const [path, query] = ...split('?');
```

Or use methods available for `Url` class when instantiated on the path.

2024-02-06 15:42 UTC, Liubov-crypto commented
LGTM

2024-02-06 15:42 UTC, peronczyk commented on src/popup/pages/InviteClaim.vue
> +import { useInvites, useModals, useUi } from '../../composables';
```suggestion
import { useInvites, useModals, useUi } from '@/composables';
```

2024-02-06 21:22 UTC, peronczyk approved these changes

2024-02-07 08:41 UTC, Liubov-crypto commented
Retested, LGTM

2024-02-07 08:44 UTC, merged