fix: do not call cordova mnemonic migration on extension
superhero-com/superhero-wallet pull request #2717
Opened 2024-02-16 11:52 UTC by martinkaintas

closes #2713 
Even though the actual migration was not being called because of the inner if check, it was still causing issues with the extension

2024-02-16 12:10 UTC, CedrikNikita approved these changes

2024-02-16 12:26 UTC, peronczyk commented on src/composables/accounts.ts
> +    migrations: RUNNING_IN_TESTS || IS_EXTENSION ? [
It's OK, but what do you think about making the 2 arrays as 1 (less quirky way)? I mean instead choosing between 2 arrays that has some duplicated items just:

```
    migrations: [
      migrateMnemonicVuexToComposable,
      (!RUNNING_IN_TESTS && !IS_EXTENSION) && migrateMnemonicCordovaToIonic,
    ].filter(excludeFalsy),
```

2024-02-16 12:26 UTC, peronczyk approved these changes

2024-02-20 10:00 UTC, CedrikNikita commented on src/composables/accounts.ts
> +      ...(!(RUNNING_IN_TESTS || IS_EXTENSION) ? [migrateMnemonicCordovaToIonic] : []),
I think it is suppose to be run only on previously Cordova based platforms.

2024-02-20 10:10 UTC, CedrikNikita requested changes
This code is not working for an reverse iframe scenario.

2024-02-20 11:12 UTC, martinkaintas commented
> It's working in Chrome but doesn't work in FF:

You need to allow the extension to run on the DEX

2024-02-20 12:37 UTC, CedrikNikita approved these changes

2024-02-20 12:39 UTC, merged