Fix: Multisig active transaction card padding
superhero-com/superhero-wallet pull request #2758
Opened 2024-02-27 08:37 UTC by peronczyk

2024-02-28 15:38 UTC, Liubov-crypto commented
LGTM

2024-02-29 04:50 UTC, CedrikNikita requested changes
Loader in this `Panel` are now not centered.
![image](https://github.com/superhero-com/superhero-wallet/assets/9008074/8bb29786-7235-4b97-ae4d-03b448f63605)

2024-03-04 10:29 UTC, peronczyk commented
> Loader in this `Panel` are now not centered.

Fixed. Please see now.

2024-03-05 09:13 UTC, CedrikNikita approved these changes

2024-03-05 09:16 UTC, merged