Support payForTx, typed data, delegation signing with a basic confirmation
superhero-com/superhero-wallet pull request #2783
Opened 2024-03-04 05:54 UTC by davidyuk

This PR is supported by the Æternity Foundation

I've tested it using https://docs.aeternity.com/aepp-sdk-js/v13.2.2/examples/browser/aepp/

Take over this PR to implement confirmations as you need 🙏

2024-03-05 12:19 UTC, Liubov-crypto commented
LGTM

2024-03-19 10:11 UTC, peronczyk commented on src/protocols/aeternity/libs/AeAccountHdWallet.ts
> +      const opt = {
I suggest to use more descriptive name instead of shortening the argument.

2024-03-19 10:20 UTC, peronczyk approved these changes

2024-03-19 10:28 UTC, CedrikNikita requested changes
This code is should be rewritten to not depend on sing message permissions. Because connected dapp in the current implementation with **silently** ask for delegations, if the auto sign message is turned on in the permissions.

2024-05-02 12:04 UTC, CedrikNikita approved these changes

2024-05-02 13:55 UTC, davidyuk commented on src/protocols/aeternity/libs/AeAccountHdWallet.ts
> +          message = `sign delegation of ${resolvedName || params.nameId} to ${params.contractAddress}`;
```suggestion
          message = `sign delegation of ${resolvedName ?? params.nameId} to ${params.contractAddress}`;
```

2024-05-02 13:55 UTC, davidyuk commented on src/protocols/aeternity/libs/AeAccountHdWallet.ts
> +          message = `sign delegation of name claiming to ${params.contractAddress}`;
```suggestion
          message = `sign delegation of all names management to ${params.contractAddress}`;
```
> AENS_CLAIM, AENS_UPDATE, AENS_TRANSFER, AENS_REVOKE

https://github.com/aeternity/protocol/blob/8a9d1d1/contracts/fate.md#appendix-2-delegation-signatures

2024-05-02 13:55 UTC, davidyuk commented on src/protocols/aeternity/libs/AeAccountHdWallet.ts
> +      aeppOrigin: undefined,
```suggestion
      networkId: this.nodeNetworkId.value,
```
MemoryAccount won't pass these options to `sign` method
https://github.com/aeternity/aepp-sdk-js/blob/2743e4af828902d90e532447b6c526c833869e49/src/account/Memory.ts#L207-L217

2024-05-10 09:56 UTC, Liubov-crypto commented
I can delegate signature. 
But not all functions will work, for example if I want Generate spend transaction or Sign inner transaction or Pay for transaction , Deploy or Call Contract here https://docs.aeternity.com/aepp-sdk-js/v13.2.2/examples/browser/aepp/  
I will get an error: UnsupportedVersionError: Unsupported node version 7.0.0. Supported: >= 6.2.0 < 7.0.0

2024-05-10 14:17 UTC, Liubov-crypto commented
I'm still getting an issue with UnsupportedVersionError: Unsupported node version 7.0.0. Supported: >= 6.2.0 < 7.0.0

![geni](https://github.com/superhero-com/superhero-wallet/assets/69896204/d16fafe1-10f9-4849-9899-c4afd825b53e)
![sp](https://github.com/superhero-com/superhero-wallet/assets/69896204/47558308-225b-499a-b00b-6cd51a586cd6)

2024-05-10 15:07 UTC, Liubov-crypto commented
LGTM, tested in testnet

2024-05-10 15:18 UTC, merged