refactor: qr scanner modal safari camera permissions
superhero-com/superhero-wallet pull request #2942
Opened 2024-04-04 14:06 UTC by peronczyk

2024-04-05 05:14 UTC, CedrikNikita requested changes
Close/cancel scanning `X` button doesn't work in Android.

2024-04-05 09:21 UTC, martinkaintas approved these changes

2024-04-05 09:29 UTC, peronczyk commented on src/popup/components/Modals/QrCodeReader.vue
> +    This modal is displayed only on web and extension.
@martinkaintas please see my updated comment. I wanted to clearly describe the difference between the mobile and web use case.

2024-04-05 09:30 UTC, peronczyk commented
> Close/cancel scanning `X` button doesn't work in Android.

Fixed. Can you confirm?

2024-04-08 14:29 UTC, Liubov-crypto commented
LGTM

2024-04-09 06:44 UTC, merged