feat(wallet-connect): support deeplinks
superhero-com/superhero-wallet pull request #3246
Opened 2024-08-27 10:45 UTC by CedrikNikita

fixes #3220

2024-08-28 08:31 UTC, martinkaintas requested changes

2024-08-28 08:31 UTC, martinkaintas commented on src/composables/walletConnect.ts
> +  function cloaseAppIfOpenUsingDeeplink() {
```suggestion
  function closeAppIfOpenUsingDeeplink() {
```

2024-08-28 08:49 UTC, martinkaintas approved these changes

2024-08-29 14:49 UTC, Liubov-crypto commented
This seems not to be fixed. I have to open app manually to confirm the Tx: 


https://github.com/user-attachments/assets/a34b4a75-d2c3-41ac-bf26-b0cbd449df05

2024-08-30 08:09 UTC, CedrikNikita commented
> This seems not to be fixed. I have to open app manually to confirm the Tx:

New logic would only work if user was initially redirected to the wallet via deeplink.

2024-08-30 09:19 UTC, Liubov-crypto commented
retested, LGTM

2024-08-30 09:52 UTC, merged